### ISSUE TITLE
RSVP status not shown in Listview

### ISSUE THREAD

**Issue by EidolonForgery** [DistantEye/HappeningsDotNetC#2]
Steps to reproduce:
Have events where you have RSVP'd and select Calendar List View (Agenda):

![08-IrbXfuR](https://user-images.githubusercontent.com/5998409/62407689-7592d600-b571-11e9-8bb5-a0e890b64de2.png)

**Comment by DistantEye** [comment]
Should be fixed for latest, including variable display between the logged in user's status if filter set to null or that user, or the filtered user's status if filtering on them

**Comment by EidolonForgery** [comment]
Fixed in commit [b5dec8c](https://github.com/DistantEye/HappeningsDotNetC/commit/b5dec8c99321fed7c8a16312a33e13cca7c0aaa0)
