### ISSUE TITLE
Multi-Day Events are not marked across multiple days in Calendar view

### ISSUE THREAD

**Issue by EidolonForgery** [DistantEye/HappeningsDotNetC#3]
Create any event and set its end-date more than 24 hours after its start date. Only the beginning of the event will show.

![08-IZYiWJK](https://user-images.githubusercontent.com/5998409/62407734-58123c00-b572-11e9-95e8-36435b78dd74.png)

**Comment by DistantEye** [comment]
Should be fixed in latest, although this one will probably still need more edge case probing to make sure

**Comment by EidolonForgery** [comment]
Confirmed
